input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [1, Conv, [16, 3, 2, null, 1, "HardSwish"]],
        # k t c SE HS s
        ## MDConv
          # out_planes,
          # expand_ratio,
          # kernel_size,
          # stride,
          # reduction_ratio=4,
          # drop_connect_rate=0.0,
        [1, MBConv, [16, 4, 3, 1]],
        [1, MBConv, [24, 4, 3, 2]],
        [1, MBConv, [24, 4, 3, 1]],
        [1, MBConv, [40, 4, 3, 2]],
        [1, MBConv, [40, 4, 3, 1]],
        [1, MBConv, [40, 4, 3, 1]],
        [1, MBConv, [80, 4, 3, 2]],
        [1, MBConv, [80, 4, 3, 1]],
        [1, MBConv, [80, 4, 3, 1]],
        [1, MBConv, [80, 4, 3, 1]],
        [1, MBConv, [112, 4, 3, 1]],
        [1, MBConv, [112, 4, 3, 1]],
        [1, MBConv, [160, 4, 3, 2]],
        [1, MBConv, [160, 4, 3, 1]],
        [1, MBConv, [160, 4, 3, 1]],
        [1, MBConv, [320, 4, 3, 2]],
        [1, MBConv, [320, 4, 3, 1]],
        
        [1, Conv, [960, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, Conv, [1280, 1, 1]],
        [1, Flatten, []],
        [1, Linear, [6]]
    ]

    